# Generated by Django 4.2.11 on 2026-03-29 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatquery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chat Query', 'verbose_name_plural': 'Chat Queries'},
        ),
        migrations.AddField(
            model_name='chatquery',
            name='confidence',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='chatquery',
            name='intent',
            field=models.CharField(choices=[('buy_query', 'Buy Query'), ('sell_query', 'Sell Query'), ('portfolio_review', 'Portfolio Review'), ('market_overview', 'Market Overview'), ('explain_stock', 'Stock Explanation'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='chatquery',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('BUY', 'Buy'), ('HOLD', 'Hold'), ('AVOID', 'Avoid'), ('WATCH', 'Watch'), ('', 'None')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='chatquery',
            name='symbol',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatquery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatquery',
            index=models.Index(fields=['user', '-created_at'], name='ai_engine_c_user_id_2d6f49_idx'),
        ),
        migrations.AddIndex(
            model_name='chatquery',
            index=models.Index(fields=['symbol'], name='ai_engine_c_symbol_bed873_idx'),
        ),
    ]
